### ISSUE TITLE
Help setting this up with an already running homebridge instance

### ISSUE THREAD

**Issue by vvn0687** [fbx/homebridge-freebox-home#3]
Hey,

I'm already running homebridge and homebridge-Camera-FFmpeg (1.2.2)

Assuming I've installed the required plugins (http-security-system / pir-motion-sensor / contact-sensor), how can I pair my homebridge instance with the freebox-api ?

Thanks for your time.

**Comment by Que20** [comment]
In the case where you already have a running instance of Homebridge, I recommend following the [Usage](https://github.com/fbx/homebridge-freebox-home#usage) part of the readme, **skipping** the steps _Start Homebridge_ and _Create the Homebridge conf file_.
Once homebridge-freebox-home is running and has granted access to the freebox home api, edit your Homebridge configuration adding accessories as follow:
- For a door/window sensor:
Replacing the `localhost` by the IP your homebridge-freebox-home is running on, and replacing `9` by your contact sensor's node id. You can find the id calling manually the API on a browser at [http://mafreebox.freebox.fr/api/v6/home/nodes](http://mafreebox.freebox.fr/api/v6/home/nodes).
```
{
  "accessory": "ContactSensor",
  "name": "Détecteur d'ouverture",
  "pollInterval": 1000,
  "statusUrl": "http://localhost:8888/api/node/9"
}
```
- For a motion sensor:
Also replacing `localhost` and the id (here `11`)
```
{
  "accessory": "motion-sensor",
  "name": "Détecteur de mouvements",
  "pollInterval": 1000,
  "statusUrl": "http://localhost:8888/api/node/11"
}
```
- For the alarm:
```
{
  "accessory": "Http-SecuritySystem",
  "name": "Alarme",
  "username": "",
  "password": "",
  "immediately": false,
  "polling": true,
  "pollInterval": 3000,
  "http_method": "GET",
  "urls": {
    "stay": {
      "url": "http://localhost:8888/api/alarm/home",
      "body": null
    },
    "away": {
      "url": "http://localhost:8888/api/alarm/main",
      "body": null
    },
    "night": {
      "url": "http://localhost:8888/api/alarm/secondary",
      "body": null
    },
    "disarm": {
      "url": "http://localhost:8888/api/alarm/off",
      "body": null
    },
    "readCurrentState": {
      "url": "http://localhost:8888/api/alarm/state",
      "body": null
    },
    "readTargetState": {
      "url": "http://localhost:8888/api/alarm/target",
      "body": null,
      "headers": {
        "Content-Type": "text/html"
      }
    }
  }
}
```
- For a camera:
You have to first manually enable the rtsp feed on the camera, calling
```
http://{camera_login}:{camera_password}@{camera_ip}/adm/set_group.cgi?group=H264&sp_uri=live
```
You will find your camera's login, password and ip on your freebox iOS/Android app.
Then add it as a Camera-ffmpeg platform's camera, replacing {camera_ip} by the camera's ip, like so:
```
{
  "name": "Caméra",
  "manufacturer": "Freebox",
  "model": "RocketCam",
  "serialNumber": "133717",
  "motion": true,
  "videoConfig": {
    "source": "-re -i rtsp://{camera_ip}/live",
    "maxStreams": 1,
    "maxWidth": 1280,
    "maxHeight": 720,
    "maxBitrate": 1000,
    "maxFPS": 15,
    "audio": false,
    "additionalCommandline": "-pix_fmt yuv420p -x264-params intra-refresh=1:bframes=0"
  }
}
```

**Comment by vvn0687** [comment]
Hey,

Sorry for the late feedback.

I've finally managed to set things up and running but ran into some issues :

- this version of the gateway wouldn't simply pair to my freebox (no notification on LCD screen) so I used yours from https://github.com/Que20/homebridge-freebox-home and it connected flawlessly. I authorized it on the LCD screen and granted access through FreeboxOS.

- the problem with the "old" gateway was that the alarm would reset to home state after a while.

Eventually, I switched back to this version using the credentials (.store) generated by "your" gateway.

Merci.

**Comment by Que20** [comment]
The version from my repo isn't maintained. I do not recommend using id.

You did start the server with the auto-auth param ?
`npm run start -- auto-auth` (with spaces before **and** after `--`)

You can manually request a freebox auth by requesting :
[GET] host:8888/api/fbx/auth

Anyway, I'm glad you found a solution.

Bon courage :)
