### ISSUE TITLE
Rapsberry 4

### ISSUE THREAD

**Issue by argagne** [fbx/homebridge-freebox-home#4]
hi,

when i try to install your plugin on a Rapsberry 4, i have this error:
 sudo npm run start -- auto-auth

> freebox-home-api@1.0.0 start /home/pi/homebridge-freebox-home
> node src/index.js "auto-auth"

/home/pi/homebridge-freebox-home/node_modules/better-logging/dist/lib/logger.js:30
        const implementationArray = [implementation].flatMap(v => v)
                                                     ^

TypeError: [implementation].flatMap is not a function
    at new LoggerContext (/home/pi/homebridge-freebox-home/node_modules/better-logging/dist/lib/logger.js:30:54)
    at Object.exports.CustomInstance (/home/pi/homebridge-freebox-home/node_modules/better-logging/dist/api.js:17:22)
    at Object.<anonymous> (/home/pi/homebridge-freebox-home/node_modules/better-logging/dist/api.js:20:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freebox-home-api@1.0.0 start: `node src/index.js "auto-auth"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freebox-home-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-07-24T08_51_05_841Z-debug.log
pi@raspberrypi:~/homebridge-freebox-home $ sudo npm run start -- auto-auth

> freebox-home-api@1.0.0 start /home/pi/homebridge-freebox-home
> node src/index.js "auto-auth"

can you help me to install on a rapsberry for have one Homebridge install for my all domo ?
Thanks

**Comment by Que20** [comment]
Can you provide your setup spec ? node & npm version ?

**Comment by argagne** [comment]
node v10.21.0
npm v6.14.7
Linux raspberrypi 5.4.51-v7l+ #1327 SMP

**Comment by Que20** [comment]
So you are about 6 major version behind the supported node version.
I suggest you use the `n` node version manager.
```
sudo npm install -g n
sudo n 12.16.2
```
This will update your node to 12.16.2.

**Comment by argagne** [comment]
thanks it's better.
root@raspberrypi:/home/pi/homebridge-freebox-home# sudo npm run start -- auto-auth

> freebox-home-api@1.0.0 start /home/pi/homebridge-freebox-home
> node src/index.js "auto-auth"

[14:36:49][7/24/2020] [-] Store file already present
[14:36:49][7/24/2020] [!] Token has nil value

but nothing on the freebox ...

**Comment by Que20** [comment]
Remove the auto-auth parameter, I need to update the readme.
This parameter should be there only if you already have credentials.

**Comment by argagne** [comment]
the same : sudo npm run start

> freebox-home-api@1.0.0 start /home/pi/homebridge-freebox-home
> node src/index.js

[15:02:56][7/24/2020] [-] Store file already present
[15:02:56][7/24/2020] [!] Token has nil value

**Comment by Que20** [comment]
What happened here is the previous start (auto-auth) created a store file with a nul value.
You have to delete it (src/.store) and re-run the serveur.
Another option would be to manually request credentials buy calling this endpoint :
`http://{your_raspberry_pi_ip_adresse}:8888/api/fbx/auth`

**Comment by Que20** [comment]
I might rename the `auto-auth` by something more consistent and less deceptive like `use-stored-cred`, and create a "real" auto-auth.

**Comment by argagne** [comment]
ok i'm not an expert on Linux sorry, 
where i delete the (src/.store) ?
and http://{your_raspberry_pi_ip_adresse}:8888/api/fbx/auth with the ip of the raspberry is page not found.
with a netstat, nothing listen on 8888 ...
Thanks

**Comment by Que20** [comment]
Make sure your server is running (sudo npm run start) while requesting the `api/fbx/auth`.
To delete the .store, simply go on the cloned repository, and type `rm src/.store`.

**Comment by argagne** [comment]
ok is good after restart the server, i try ta view the authentication on the freebox and give the rights on freeboxOS.
But when i go on http://rapsberry:8888/api/homebridge/conf, i have a connection refused.

**Comment by Que20** [comment]
Ok. Not sure I got your last message.

Before calling homebridge/conf, make sure :
1. The server is still running.
2. You have a running Homebridge instance.
3. All three permissions required has been granted on FreeboxOS.

**Comment by argagne** [comment]
it work, but not  automatically, i do start the server, how i can run this instance automaticaly when raspberry start or on service ?

**Comment by Que20** [comment]
To make you raspberry pi automatically start the server and homebridge, I suggest to use PM2 as a process manager.
```
sudo npm install -g pm2
```
Start Homebridge
```
pm2 start homebridge
```
Start Homebridge-Freebox-Home
```
pm2 start src/index.js
```
then save the config, and add to startup
```
pm2 save
pm2 startup
```
