### ISSUE TITLE
Lancer l'authentification - erreur

### ISSUE THREAD

**Issue by GotierLdl** [fbx/homebridge-freebox-home#5]
Bonjour,

J'ai déjà un serveur Homebridge (192.168.0.3) (hébergé sur Windows qui fonctionne super bien) et il est déconseillé d'avoir plus d'un serveur HB sur un même réseau. J'ai donc installé tous les plugins en déchiffrant les sources (novice).
Hors quand j'ajoute tous mes objets connectés j'ai un retour (fermé pour la porte par exemple) mais aucun retour de changement d'état. 

je pense que cela vient de l'authentification sur la box mais je n'arrive pas à lancer celle-ci sur le Freebox via `npm run start -- auto-auth`

je me retrouve sur cette erreur : 
`C:\Windows\System32>cd homebridge-freebox-home

C:\Windows\System32\homebridge-freebox-home>npm run start -- auto-auth

> freebox-home-api@1.0.0 start C:\Windows\System32\homebridge-freebox-home
> node src/index.js "auto-auth"

internal/modules/cjs/loader.js:1017
  throw err;
  ^

Error: Cannot find module 'express'
Require stack:
- C:\Windows\System32\homebridge-freebox-home\src\index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Windows\System32\homebridge-freebox-home\src\index.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ 'C:\\Windows\\System32\\homebridge-freebox-home\\src\\index.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! freebox-home-api@1.0.0 start: `node src/index.js "auto-auth"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the freebox-home-api@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Gauthier LOURDEL\AppData\Roaming\npm-cache\_logs\2020-12-17T17_55_22_719Z-debug.log`

Depuis homebridge les logs me donne uniquement un `Error: connect ECONNREFUSED 192.168.0.3:8888`

Merci d'avance pour votre aide.

**Comment by GotierLdl** [comment]
je fourni le log : 
`0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Gauthier LOURDEL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   'auto-auth'
1 verbose cli ]
2 info using npm@6.14.9
3 info using node@v14.0.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle freebox-home-api@1.0.0~prestart: freebox-home-api@1.0.0
6 info lifecycle freebox-home-api@1.0.0~start: freebox-home-api@1.0.0
7 verbose lifecycle freebox-home-api@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle freebox-home-api@1.0.0~start: PATH: C:\Users\Gauthier LOURDEL\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Windows\System32\homebridge-freebox-home\node_modules\.bin;C:\Users\Gauthier LOURDEL\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Program Files\PuTTY\;C:\ffmpeg\bin;C:\Users\Gauthier LOURDEL\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle freebox-home-api@1.0.0~start: CWD: C:\Windows\System32\homebridge-freebox-home
10 silly lifecycle freebox-home-api@1.0.0~start: Args: [ '/d /s /c', 'node src/index.js "auto-auth"' ]
11 silly lifecycle freebox-home-api@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle freebox-home-api@1.0.0~start: Failed to exec start script
13 verbose stack Error: freebox-home-api@1.0.0 start: `node src/index.js "auto-auth"`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Gauthier LOURDEL\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Gauthier LOURDEL\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1051:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid freebox-home-api@1.0.0
15 verbose cwd C:\Windows\System32\homebridge-freebox-home
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Gauthier LOURDEL\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "start" "--" "auto-auth"
18 verbose node v14.0.0
19 verbose npm  v6.14.9
20 error code ELIFECYCLE
21 error errno 1
22 error freebox-home-api@1.0.0 start: `node src/index.js "auto-auth"`
22 error Exit status 1
23 error Failed at the freebox-home-api@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]`

**Comment by Que20** [comment]
Bonjour,
Il vous manque visiblement la dependance express.
