### ISSUE TITLE
Installer Freebox Home sur server Homebridge.

### ISSUE THREAD

**Issue by gfbourreau** [fbx/homebridge-freebox-home#6]
Bonjour,
Je suis sur cette page car l'assistance Freebox Home partage ce lien pour l'installation du pack Sécurité sur un serveur Homebridge classique.
Cependant je n'y arrive pas.
Je suis bloqué dès les 1ères lignes de commandes...
On dirait la construction d'un server Homebridge-Freebox-Home , et non l'implantation d'un plugin Freebox Home sur un serveur distinct?

Merci pour votre aide

**Comment by Que20** [comment]
Bonjour,
Effectivement, comme décrit dans le readme, il ne s'agit pas d'un plugin Homebridge mais d'un serveur pont pour interfacer Homebridge et les plugins http.
Ce que vous pouvez faire c'est cloner, puis lancer le serveur sur une machine, lancer une authentification, puis ajouter manuellement les plugins sur votre serveur Homebridge.

**Comment by gfbourreau** [comment]
Bonjour et merci.
Pardonnez mon faible niveau mais bon... il faut bien commencer.
Cloner quoi?
J'ai réussi à installé un server Homebridge en VM sur le server Delta à l'aide de  [https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Debian-or-Ubuntu-Linux](url)
Je me suis connecté et authentifié. Ca à l'air de fonctionner.

De quels plugins parlez-vous?
Homebridge Http Contact Sensor?
Homebridge Http Pir Motion Sensor?
Homebridge Http Securitysystem?
J'ai réussi à les  installer je ne sais pas trop comment avec les lignes de commande mentionnées ici. Et non avec l'interface GU d'Homebridge
Mais je n'arrive pas à les ouvrir, et je n'ai jamais l'évenement d'authentification sur le server Delta à validé.

**Comment by gfbourreau** [comment]
Bonjour Que20.
Pourriez-vous svp m'indiquer les étapes 1à1....dsl.
Après avoir installer un serveur Homebridge.
Je clone le repo (git clone https://github.com/fbx/homebridge-freebox-home.git)?
Ensuite? Je ne comprend pas lancer le server sur une machine?
Si je passe de suite à l'étape (npm run start -- auto-auth) cela m'indique.

npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/freebox/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/freebox/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/freebox/.npm/_logs/2021-01-09T09_41_45_275Z-debug.log

Merci.

**Comment by gfbourreau** [comment]
Bonjour,
Pardonnez-mon insistance.. mais je n'y arrive pas...
Vous êtes membre de l'équipe Freebox Home?
Je ne voudrais pas polluer cette page, peut-être pourriez-vous m'apporter votre aide sur un sujet que j'ai ouvert sur le forum:
https://freebox.toosurtoo.com/forum/viewtopic.php?f=120&t=25714&sid=ec997ee92b3485207b7b3e93d18763b7

Merci,
Geoffroy.

**Comment by Que20** [comment]
Bonjour,
Oui, je suis membre de l'équipe Freebox Home.
Le principe de ce projet est de créer une interface pour laisser communiquer des plugins http (par exemple homebridge-http-contact-sensor).

Les étapes sont dans le readme, mais je peux vous les remettre ici.
Avant tout, assurez vous d'avoir une version récente de Node et npm. J'utilise la 12.16.2 de node, et la latest de npm.
Pour gérer la version de node vous pouvez utiliser `n`. (`npm install -g n` pour installer et lancez `n <version>` par exemple `n 12.16.2` - assurez-vous d’être root).
Pour utiliser ce projet, après l'avoir cloné, allez dans le répertoire homebridge-freebox-home, et installez y les dépendances avec `npm install`. Pour les plugins, lancez `homebridge-install`. Si vous ne pouvez pas lancer ce script, vous pouvez manuellement installer les plugins :
- homebridge-http-securitysystem
- homebridge-http-contact-sensor
- homebridge-http-pir-motion-sensor

Si vous utilisez la caméra, installez les paquets suivants :
- ffmpeg (attention ce n'est pas un plugin hb, mais un paquet)
- homebridge-camera-ffmpeg

Une fois les plugins installés, vous pouvez lancer le serveur :
`npm run start`
Puis lancez une demande d’authentification avec `127.0.0.1:8888/api/fbx/auth` (validez sur le LCD de votre freebox).
Accordez ensuite les droits à l'application dans freeboxOS.

Consultez les IDs des objets avec `127.0.0.1:8888/api/node/list`. Cela vous renverra quelque chose de ce type :
```
[
  {
    "id": 63,
    "type": "alarm"
  },
  {
    "id": 66,
    "type": "camera"
  },
  {
    "id": 68,
    "type": "dws"
  }
]
```
Vous pouvez maintenant manuellement ajouter les plugins dans la conf homebridge.
Manuellement, donc, pour chaque entrée de cette liste, dans votre configuration homebridge, ajoutez les lignes suivante :

- Pour un "dws" (détecteur d'ouverture) :
```
     {
         "accessory":"ContactSensor",
         "name":"<Mon détecteur d'ouverture>",
         "pollInterval":1000,
         "statusUrl":"http://localhost:8888/api/node/<ID>"
     }
```
- Pour un "pir" (détecteur de mouvements) :
```
     {
         "accessory":"motion-sensor",
         "name":"<Mon détecteur de mouvements>",
         "pollInterval":1000,
         "statusUrl":"http://localhost:8888/api/node/<ID>"
     }
```
- Pour l'alarme :
```
    {
         "accessory":"Http-SecuritySystem",
         "name":"Alarme",
         "username":"",
         "password":"",
         "immediately":false,
         "polling":true,
         "pollInterval":3000,
         "http_method":"GET",
         "urls":{
            "stay":{
               "url":"http://localhost:8888/api/alarm/home",
               "body":null
            },
            "away":{
               "url":"http://localhost:8888/api/alarm/main",
               "body":null
            },
            "night":{
               "url":"http://localhost:8888/api/alarm/secondary",
               "body":null
            },
            "disarm":{
               "url":"http://localhost:8888/api/alarm/off",
               "body":null
            },
            "readCurrentState":{
               "url":"http://localhost:8888/api/alarm/state",
               "body":null
            },
            "readTargetState":{
               "url":"http://localhost:8888/api/alarm/target",
               "body":null,
               "headers":{
                  "Content-Type":"text/html"
               }
            }
         }
      }
```
Pour la caméra c'est un peu plus compliqué car il faut activer le RTSP sur chacune de vos caméras, puis ajouter en homebridge plateforme :
```
{
    "name": "<Ma caméra>",
    "manufacturer": "Freebox",
    "model": "RocketCam",
    "serialNumber": '1337'+cam.id,
    "motion": true,
    "videoConfig": {
        "source": "-re -i rtsp://<ip de la camera>/live",
        "maxStreams": 1,
        "maxWidth": 1280,
        "maxHeight": 720,
        "maxBitrate": 1000,
        "maxFPS": 15,
        "audio": false,
        "additionalCommandline": "-pix_fmt yuv420p -x264-params intra-refresh=1:bframes=0"
    }
}
```
En remplaçant le localhost par l'ip de la machine sur laquelle le serveur homebridge-freebox-home est installée. Ici j'ai mis localhost.
Remplacez aussi les `<ID>` et par les bons ID des objets, et le nom que vous voulez leur donner dans HomeKit (`<Mon détecteur de mouvements>`).

Tout ce processus se fait automatiquement si vous utilisez un serveur HB dédié à freebox home (que vous pourrez modifier ensuite pour vos objets) avec l'url de config (/homebridge/conf).
Ce sont là les étapes manuelles.

**Comment by gfbourreau** [comment]
Bonjour,
Peut-être me suis-je mal exprimé, mais je n'y arrive toujours pas, dsl...
Vous m'expliquez (j'ai l'impression...) comment installer manuellement la configuration d'un server Homebridge, en lieu et place de celui installé automatiquement (et je vous en remercie!!!).
Mais ce que j'aimerai (et ce qui est indiqué sur le l'assistance freebox) c'est l'ajout du pack security sur un server homebridge déjà existant. Et ça, malgré vos infos précieuses, je n'y arrive pas.

Il y a t'il un moyen de se connecter à l'homebridge-freebox en interface graphique (comme n'importe quel server homebridge) et pouvoir par la suite y ajouter d'autre plugins? (je n'y arrive pas).

Ou il y a t'il un moyen à un server Homebridge classique d'ajouter le pack security de la delta?

Je ne parviens jamais à lancer une authentification avec 127.0.01:8888/api/fbx/auth

Pardonner mes compétences.... 
Merci,
Geoffroy.

**Comment by Que20** [comment]
Pour installer le pack secu sur un serveur HB, il faut passer par l'installation d'un serveur homebridge-freebox-home.
Ce serveur doit **cohabiter avec** Homebidge sur votre réseau. C'est ce que je vous explique en première partie de mon précédent message.
En passant par les étapes que proposent le readme, les script se chargent d'installer Homebridge et homebridge-freebox-home ainsi que les configurations nécessaires à chacun des programmes.
Ainsi, si vous avez déjà un serveur HB dans votre réseau, suivez les instructions au dessus pour installer un serveur homebridge-freebox-home sans installer homebridge, et ajoutez les plugins à votre HB existant comme expliqué dans mon message.

> Le principe de ce projet est de créer une interface pour laisser communiquer des plugins http (par exemple homebridge-http-contact-sensor) et les API freebox home.
homebridge-freebox-home n'a pas d'interface graphique. On communique avec le serveur par des url.

Je constate une erreur dans l'url de votre message : c'est 127.0.0.1 et non 127.0.01
Si vous avez lancé votre serveur mais il ne vous est pas possible de lancer une authentification, je vous prierai d'ouvrir une nouvelle Issue et d'y joindre les logs sur le serveur.

Encore une fois : homebridge-freebox-home n'est pas un plugin homebridge, ce n'est pas non plus une version de homebridge. C'est un serveur indépendant qui doit cohabiter avec homebridge. Que ce soit votre installation de homebridge ou une instance installée automatiquement par les scripts d'initialisation du projet.

Pour finir, ce projet nécessite un minimum de prérequis en nodeJS et en homebridge. Il n'est pas voué à être installé sur des serveurs de production et encore moi à être distribué. Il s'agit là d'une solution open source suggérée pour proposer une alternative à l'API de freebox home pour pouvoir plus facilement communiquer avec d'autres outils (ici homebridge). Voyez plus le projet comme un proxy d'API.

Je vous laisse me contacter par mail à kmaarek@freebox.fr pour les demandes spécifiques, les issues Github ne concernent que les problème techniques, bugs, ou problèmes fonctionnels. Je vais donc fermer ce thread.
